### ISSUE TITLE
Email Raoul R.

### ISSUE THREAD

**Issue by tim-pugh** [connorkuehl/clang_randstruct#20]
Emailed Rivas to see if he can facilitate a meeting between the team and Topper who is the second highest contributor to Clangs umbrella project, LLVM.

**Comment by backseatcrew** [comment]
I have emailed Craig directly as well, just waiting to hear back from that.

If all else fails, I'll create a linkedin and send him a connection message...

**Comment by tim-pugh** [comment]
Got a response from Raoul and sent back the information he requested. Waiting to hear back.

He said he can see what he can do provided I give him some responses on specifics.

**Comment by tim-pugh** [comment]
Emailed him a final time today. If he gets back to us, I'll re-open the ticket.
