### ISSUE TITLE
Email Lattner

### ISSUE THREAD

**Issue by tim-pugh** [connorkuehl/clang_randstruct#21]
Email sent out. Person is the original author and lead of the LLVM umbrella project for Clang and Clang itself.

It appears he works at Goog too, so I'm waiting to hear a response back from our sponsor to to see if he may be able to reach out.

No harm in going to the direct source 👍

**Comment by backseatcrew** [comment]
@Jafosterja Can you remind me to ping Kees? I've emailed him already, but I just want to allow him a week or so before I reach out again.

**Comment by tim-pugh** [comment]
Got a response back from Chris and archived. Closing
