### ISSUE TITLE
make code standards pretty printer

### ISSUE THREAD

**Issue by jcantrell** [connorkuehl/clang_randstruct#3]

**Comment by jcantrell** [comment]
note: gnu indent looks useful

**Comment by connorkuehl** [comment]
How about [clang-format](https://clang.llvm.org/docs/ClangFormat.html)?

**Comment by tim-pugh** [comment]
@jcantrell https://clang.llvm.org/docs/ClangFormat.html appears to be the right route. Let me know if you need a test subject for doing merge tests on a separate branch. I'll be around.

**Comment by connorkuehl** [comment]
Have we settled on `clang-format` as our style guide? Should we close this?

**Comment by tim-pugh** [comment]
Yep ill close it now.
