### ISSUE TITLE
Build Clang on Cloud Resources

### ISSUE THREAD

**Issue by jcantrell** [connorkuehl/clang_randstruct#4]

**Comment by backseatcrew** [comment]
Ran into a build error in the workshop. Still working on this. Currently the VM is shut down.

Jordan and James have accounts setup (if we made them correctly in the workshop), and just need to test SSH access.

I should be able to test SSH myself then provide some instructions.

**Comment by connorkuehl** [comment]
Any progress on this?

**Comment by tim-pugh** [comment]
Working on SSH access. Uploading log shortly

**Comment by tim-pugh** [comment]
On issue #26 I think I'm encountering the same issue (view comment dated for today). I'll scrap my instance and rebuild it and follow those same instructions. Thanks @jeffreytakahashi @connorkuehl

**Comment by tim-pugh** [comment]
The issue was similar I should mention. I'm going to skip all optional items.

**Comment by tim-pugh** [comment]
svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm
cd llvm/tools
svn co http://llvm.org/svn/llvm-project/cfe/trunk clang
cd ../..
mkdir build
cd build
sudo apt install cmake
cmake -G "Unix Makefiles" ../llvm

**Comment by tim-pugh** [comment]
-- Targeting X86
-- Targeting XCore
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Clang version: 8.0.0
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
-- Could NOT find Z3 (missing: Z3_LIBRARIES Z3_INCLUDE_DIR) (Required is at least version "4.7.1")
CMake Warning (dev) at utils/benchmark/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Failed to find LLVM FileCheck
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_FNO_EXCEPTIONS
-- Performing Test HAVE_CXX_FLAG_FNO_EXCEPTIONS - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/timpugh_pdx_edu/build

**Comment by tim-pugh** [comment]
make -j 8

**Comment by tim-pugh** [comment]
Memory exhausted at 95% and build failed.

restarting

make -j 8

**Comment by tim-pugh** [comment]
memory exhausted again but appears to have be continuing. Error is here at 96%:

Scanning dependencies of target llvm-dwarfdump
[ 96%] Building CXX object tools/llvm-dwarfdump/CMakeFiles/llvm-dwarfdump.dir/Statistics.cpp.o
[ 96%] Building CXX object tools/llvm-dwarfdump/CMakeFiles/llvm-dwarfdump.dir/llvm-dwarfdump.cpp.o
[ 96%] Linking CXX executable ../../bin/llvm-dwarfdump
..../..//lib./../.../libLLVMSelectionDAG.a/....://liblib//libLLVMWebAssemblyCodeGen.alibLLVMTransformUtils.a::  errorerror   addingadding  symbolssymbols::  MemoryMemory  exhaustedexhausted

error adding symbols: Memory exhausted
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
../../lib/libLLVMTransformUtils.a: error adding symbols: Memory exhausted
collect2: error: ld returned 1 exit status
tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/build.make:561: recipe for target 'bin/llvm-c-test' failed
tools/dsymutil/CMakeFiles/dsymutil.dir/build.make:508: recipe for target 'bin/dsymutil' failed
tools/clang/tools/libclang/CMakeFiles/libclang.dir/build.make:767: recipe for target 'lib/libclang.so.8' failed
tools/llc/CMakeFiles/llc.dir/build.make:254: recipe for target 'bin/llc' failed
make[2]: *** [bin/llvm-c-test] Error 1
make[2]: *** [bin/dsymutil] Error 1
make[2]: *** [lib/libclang.so.8] Error 1
make[2]: *** [bin/llc] Error 1
CMakeFiles/Makefile2:72713: recipe for target 'tools/dsymutil/CMakeFiles/dsymutil.dir/all' failed
make[1]: *** [tools/dsymutil/CMakeFiles/dsymutil.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:27944: recipe for target 'tools/clang/tools/libclang/CMakeFiles/libclang.dir/all' failed
make[1]: *** [tools/clang/tools/libclang/CMakeFiles/libclang.dir/all] Error 2
CMakeFiles/Makefile2:72954: recipe for target 'tools/llc/CMakeFiles/llc.dir/all' failed
make[1]: *** [tools/llc/CMakeFiles/llc.dir/all] Error 2
CMakeFiles/Makefile2:73705: recipe for target 'tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/all' failed
make[1]: *** [tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/all] Error 2
/usr/bin/ld: BFD (GNU Binutils for Ubuntu) 2.30 internal error, aborting at ../../bfd/merge.c:908 in _bfd_merged_section_offset

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
tools/llvm-cfi-verify/CMakeFiles/llvm-cfi-verify.dir/build.make:215: recipe for target 'bin/llvm-cfi-verify' failed
make[2]: *** [bin/llvm-cfi-verify] Error 1
make[2]: *** Deleting file 'bin/llvm-cfi-verify'
CMakeFiles/Makefile2:74052: recipe for target 'tools/llvm-cfi-verify/CMakeFiles/llvm-cfi-verify.dir/all' failed
make[1]: *** [tools/llvm-cfi-verify/CMakeFiles/llvm-cfi-verify.dir/all] Error 2
[ 96%] Built target llvm-dwarfdump
[ 96%] Built target lli

**Comment by tim-pugh** [comment]
picked back up quickly at 62%. Reached 100%.

**Comment by tim-pugh** [comment]
![image](https://user-images.githubusercontent.com/22535268/49334424-bf629100-f58a-11e8-9924-596c260789c3.png)
