### ISSUE TITLE
Store seed in plugin from cmd line

### ISSUE THREAD

**Issue by tim-pugh** [connorkuehl/clang_randstruct#55]
We will need to store the seed fed into clang randstruct throughout the randomization of the struct layouts. In this way, structs created will be shuffled in the same manner and testable.

**Comment by Jafosterja** [comment]
This one is also kinda on hold until we get the plugin to accept command line arguments. After that it should be fairly simple.

**Comment by tim-pugh** [comment]
Finished #52 . Jumping back on this tomorrow.

**Comment by tim-pugh** [comment]
Re working #52 to do pull requests. Manner for which is not as straight fwd as appears. Will continue #55 shortly

**Comment by tim-pugh** [comment]
Still plugging away at #52 , 1 more day and should resolve it (or move on from it).

**Comment by tim-pugh** [comment]
Got a PM, Jordan's going to take a look since he's got free time. I'll be free post 4pm today to see whats up

**Comment by jeffreytakahashi** [comment]
I thought we'd already covered this, the way it's managed in GCCRandstruct is there is just a .h file that stores the value and a script to generate a new value from /dev/random. Do we not want to do it this way? This seems super, super easy.

**Comment by tim-pugh** [comment]
We're going to swap routes and go do a #DEFINE and get a random number in the same manner as GCC's randstruct does.

**Comment by jeffreytakahashi** [comment]
https://github.com/torvalds/linux/blob/master/scripts/gcc-plugins/gen-random-seed.sh

**Comment by tim-pugh** [comment]
@jcantrell are going to spend some time on Wed for 30 minutes, and if we're close, extend it to 1 hour and attempt to continue on the route we're taking. If it doesn't pan out, we're going to approach it the same way Kees has done it in the GCC randstruct implementation.

**Comment by tim-pugh** [comment]
@jcantrell has been doing some work on this on PR #102

**Comment by tim-pugh** [comment]
A PR request is in for this. I'm making my way to testing this. Likely tomorrow when I have time to sit down.
