### ISSUE TITLE
E-mail Kees

### ISSUE THREAD

**Issue by jcantrell** [connorkuehl/clang_randstruct#7]
how did he test his stuff?

**Comment by backseatcrew** [comment]
also need to ask about backup contact, and if he has build instructions. Likely on the wiki page he has has so I'll take a look first.

**Comment by backseatcrew** [comment]
Done and done, I'll let ya'll know when I hear back @jcantrell

**Comment by backseatcrew** [comment]
Got the response back @jcantrell @jeffreytakahashi @nforbus @connorkuehl @Jafosterja @Nixoncole 

Closing this issue and re-opening new one for emailing Bart.
