### ISSUE TITLE
Respect __attribute((packed))__

### ISSUE THREAD

**Issue by connorkuehl** [connorkuehl/clang_randstruct#73]
Our plugin should be aware of this feature and if it is on the structure definition, it should not insert extra padding.

**Comment by connorkuehl** [comment]
The inherited [bool clang::Decl::hasAttr()](https://clang.llvm.org/doxygen/classclang_1_1Decl.html#ae7a63b99398864d86f53afd8a03c359b) may come in handy here.

**Comment by connorkuehl** [comment]
Here's an example on how to use `hasAttr()`:

c0d0a8f8ebe2577eba1e18d1b7711ebd84e74566

**Comment by jeffreytakahashi** [comment]
This is still pending work on the other, though we have started discussion of this and how we will go about testing.

**Comment by connorkuehl** [comment]
> pending work on the other,

What other?

**Comment by connorkuehl** [comment]
Closing in favor of #99
