### ISSUE TITLE
Create small unit test example(s)

### ISSUE THREAD

**Issue by tim-pugh** [connorkuehl/clang_randstruct#76]
We will need some unit tests created so others on the team can learn the testing strategies and develop them quickly.

**Comment by tim-pugh** [comment]
@jcantrell @nforbus would you be interested in scheduling a time with Bart to get advised on unit test creations and good strategies? I'd like to myself

**Comment by nforbus** [comment]
As stated previously; I'm good to meet with Bart but it appears that we're instead going to meet him as a group next week.  Additionally, I will be meeting with Chris Gilmore to talk about unit testing this week.

**Comment by nforbus** [comment]
Have worked with Jeff and Jordan to figure out how we're going to do some unit tests.  We're probably going to mash some out on Friday.

**Comment by nforbus** [comment]
Unit tests have been determined by the team to not be feasible for this project.  We are now instead pursuing using an end-to-end test process similar to the one the Constantine plug in.  Creating a new issue for that, and closing this one.
