### ISSUE TITLE
Contact llvm/Clang devs on feasability

### ISSUE THREAD

**Issue by tim-pugh** [connorkuehl/clang_randstruct#8]
Need to reach out to devs upstream for a bit of guidance between plugin vs upstream feasibility and expectations.

**Comment by backseatcrew** [comment]
Still reaching out to other individuals. We'll see what shakes loose (documented on team meeting notes).

**Comment by backseatcrew** [comment]
Email response from Richard Smith. Put into correspondence folder. Response from Eli in Google Drive as well.

**Comment by tim-pugh** [comment]
Will re-open other issues when we contact other people
