### ISSUE TITLE
Bitfields:

### ISSUE THREAD

**Issue by jeffreytakahashi** [connorkuehl/clang_randstruct#89]
@connorkuehl requested an issue be opened regarding bit fields. From our documentation below, but Connor will need to verify/specify what he wants.

Per Connor: 

> "I know there’s a situation where we do not want to mess with those but can’t recall off the top of my head. Might be in requirements doc."

Per our documentation:

> "Develop full randomization. All structures marked with __randomize_layout have field positions randomized, including bit fields.
> 
> Develop a 'performance-sensitive' mode. Best-effort limited randomization to cache-line (64-byte) size region, keeping adjacent bit fields together."

**Comment by tim-pugh** [comment]
Here is the doxygen file that has a method that checks if a field is a bit field

https://clang.llvm.org/doxygen/classclang_1_1FieldDecl.html#a15b449c8861018fe6da98822575d6cb2

**Comment by connorkuehl** [comment]
> Performance-sensitive randomization (possible stretch)
Best-effort limit randomization to cache-line (64 byte) size regions, **keep adjacent bit-fields together.**

**Comment by connorkuehl** [comment]
This looks a little more complicated. https://github.com/llvm-mirror/clang/blob/master/lib/AST/RecordLayoutBuilder.cpp#L1447

**Comment by connorkuehl** [comment]
Closing in favor of #99
